### ISSUE TITLE
None English character Tokenizer 

### ISSUE THREAD

**Issue by deansong** [GateNLP/gateplugin-ANNIE#17]
Annie Tokenizer sometimes split the words from a non-English character
e.g. 
Röhrich --> Ro hrich
Also the dots above o are missing from the string feature
I also tried German Tokenizer from German NER, same issue.

**Comment by greenwoodma** [comment]
Any chance this is related to not using the right encoding when initially loading the document?

**Comment by ianroberts** [comment]
From what I can tell this is due to Unicode normalisation forms.  If I create a document with the content:

```
Herr Röhrich said...
```

(NFC, with ö represented as a single code point `LATIN SMALL LETTER O WITH DIAERESIS` U+00F6) then Röhrich is a single Token.  Whereas a document with the content

```
Herr Röhrich said...
```

(NFD, with the ö represented as two code points `LATIN SMALL LETTER O` U+006F followed by `COMBINING DIAERESIS` U+0308) then Röhrich is three Tokens for "Ro", the combining accent, and "hrich".

**Comment by greenwoodma** [comment]
Probably means we need to tweak the rules in the tokenizer so the combining character isn't considered a change of unicode character class

**Comment by greenwoodma** [comment]
This should now be fixed. There were probably multiple ways of doing this, but I went with the easiest and consistently replaced `UPPERCASE_LETTER` with `(UPPERCASE_LETTER (NON_SPACING_MARK)*)` and the same for the `LOWERCASE_LETTER` so that we always allow a letter to be followed by one of these combining marks.
