### ISSUE TITLE
Default Gazetteer breaks when gazetteer list entry contains trailing space

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-ANNIE#18]
Apparently a trailing space is enough to prevent the DefaultGazetteer from finding a match even if there is a space after the matching text in the document (so even if the trailing space would be able to correctly match the text in the document).
How is this not a bug?

**Comment by ianroberts** [comment]
This is not a bug.  Entries with a trailing space in the `lst` file _do_ match text with the matching trailing space in the text, but there's a less-than-intuitive interaction between trailing spaces on gaz entries and the `wholeWordsOnly` parameter.

If WWO is set to true (the default) then entries with trailing spaces do not match when the trailing space is immediately followed by a non-space character, because WWO disallows matches that are followed by a character that is part of a word.

Example:

test.lst - one line containing "foo " with a trailing space

test document:
```
foo bar
foo  bar
```

With `wholeWordsOnly` set to `true` only the second foo-space matches, but with `wholeWordsOnly` set to `false` they both match.

**Comment by johann-petrak** [comment]
Thanks for telling me how this is not a bug :)
I guess having a trailing whitespace as part of a "whole word" is a rare thing to happen, linguistically, I would guess quite a bit rarer than having people add it by accident.
