### ISSUE TITLE
Add an option to JAPE to copy all features of an annotation into the one being created

### ISSUE THREAD

**Issue by greenwoodma** [GateNLP/gateplugin-ANNIE#8]
Often when writing JAPE rules you want to copy all the features of an annotation you have matched onto the annotation you are creating. You can do this easily with a java RHS, but with a simple RHS you have to enumerate each feature you want to copy. This is both inefficient (each one requires a for loop and lots of matching) and doesn't allow you to copy all features even if you don't know what they are.

One solution would be to allow the annotation to copy features from be identified in the simple RHS along side the normal key=value pairs.
This may look something like

```
Rule:Example
(
   {Lookup}
):lookup
-->
:lookup.NewAnnotation = {rule = "Example", :lookup.Lookup}
```

In this case all features of the Lookup annotation within the binding would be copied onto the new annotation

**Comment by ianroberts** [comment]
Points to consider:

 - what happens if there is more than one annotation of the selected type in the binding? Do we pick one of them and copy _its_ features or do we copy all the features from all the annotations of that type (which still gives an arbitrary "last one wins" situation but might matter if different annotations have different named features)
 - what happens if the `Lookup` (in this case) annotation also has a `rule` feature?  Do explicitly named features in the rule trump copied features from the other annotation or do we just work from left to right with the last one winning?
 - if you have more than one of these constructs copying from different annotations that have the same named feature, which one wins?

I guess all of these could be boiled down to a general "left-to-right, last one wins" strategy, and document that if you want to be sure your explicit values won't be overridden then you have to put them last, after the `:bind.Type`.

On a related note, is it an error to specify the same feature name twice in a RHS action and if you do then what happens?

```
Rule: TerribleWarning
(
  {Lookup}
):lookup
-->
:lookup.NewAnnotation = {name = "foo", kind = "broken", name = "bar"}
```

**Comment by ianroberts** [comment]
> what happens if there is more than one annotation of the selected type in the binding? Do we pick one of them and copy its features or do we copy all the features from all the annotations of that type (which still gives an arbitrary "last one wins" situation but might matter if different annotations have different named features)

Did anyone else have any preferences on this point?  Do we want to just copy the features from the first annotation coming out of `bindings.get("foo").iterator().next()` (which may not be the first in doc order) or do we process them all and potentially end up with a mixture of features from different annotations?  I'm sure 99.9% of the cases where this feature would be useful there will be exactly one annotation in `bindings.get("foo")` and it won't matter, but we have to document what happens in the 0.1% case.

**Comment by greenwoodma** [comment]
I'd say just the first one, in the same way we only copy a named feature from the first annotation we find

**Comment by ianroberts** [comment]
And extending this - do we also want to allow for `:lookup.NewAnnotation = { :lookup }` (without the `.AnnotationType` bit) to allow for cases where you know there will be one annotation in the relevant binding but you don't know what type it has (e.g. `({Person}|{Location}):ent`)?

**Comment by ianroberts** [comment]
> we only copy a named feature from the first annotation we find

The first annotation we find _that has a feature with that name_

**Comment by greenwoodma** [comment]
Makes sense to me, and I can see it being useful, so why not

**Comment by greenwoodma** [comment]
True, I suppose we could copy all features from the first annotation that has any features

**Comment by johann-petrak** [comment]
If this will almost always be used for situations where the binding contains exactly one annotation and the few situations where this is not the case have all kinds of ambiguity, why not *require* that the binding should only have one annotation so that the user can actually find the odd and potentially unexpected cases where there are more or none? If more annotations are present and a specific behaviour is needed, Java code is necessary anyway.

**Comment by greenwoodma** [comment]
I don't think that really works, as a simple RHS just has to work (or do nothing) so how would you report that it had hit the case of multiple matches? And we don't report then in the existing case either, we just assume people label things properly.

**Comment by johann-petrak** [comment]
I meant throw an exception and report the document name and offset. Could also log a warning instead. 
It was just an idea, I think in general it would be better to avoid unexpected or unpredictable actions in unexpected situations rather than silently do something without the user even being aware that there may be a problem. 
"label things properly" is usually something that needs to get done right first and that is exactly where detection could help.

**Comment by greenwoodma** [comment]
I think throwing an exception is exactly what we don't want. We already have the situation where we might have two annotations that match, and we just choose one at random, so I think we should just treat this the same and document the behaviour. Ensuring you correctly label the LHS isn't exactly difficult after all.
